fast_fsgps : main.c channel.c channel.h nav.c nav.h solve.c solve.h acquire.c acquire.h gold_codes.h gold_codes.c status.c status.h
	gcc -o fast_fsgps main.c channel.c nav.c solve.c acquire.c gold_codes.c status.c status.h -Wall -pedantic -O4 -lm
